language: node_js
node_js:
  - "8"
cache: 
  directories: 
    - node_modules
script:
  - npm build
  - npm test -- --coverage && cat ./coverage/lcov.info | coveralls
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  local-dir: build
  on:
    branch: camilla